# Generated by Django 3.1.4 on 2021-02-12 07:17

import cases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article_no', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('ONGOING', 'Ongoing')], default='ONGOING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaseIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.IntegerField()),
                ('file_year', models.IntegerField(default=cases.models.current_year)),
                ('name_of_complainant', models.CharField(max_length=200)),
                ('complainant_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargedOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_charges', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gist_of_article', models.TextField()),
                ('date_of_misconduct', models.DateField()),
                ('draft_article_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.article')),
            ],
        ),
        migrations.CreateModel(
            name='DraftChargeSheetProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_rc_no', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_charge_sheets', to='cases.case')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_submitted_by', to='accounts.office')),
                ('submitted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_submitted_to', to='accounts.office')),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfMisconduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_officer', models.CharField(max_length=100)),
                ('report_date', models.DateField(auto_now=True)),
                ('report_conclusion_breif', models.TextField()),
                ('follow_up_action', models.TextField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.designation')),
                ('draft_article', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_enquiries', to='cases.draftarticle')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
            ],
        ),
        migrations.CreateModel(
            name='SourceOfComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrelinminaryEnquiryAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=cases.models.draft_article_preliminary_enquiry_directory_path)),
                ('premilinary_enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_attachments', to='cases.preliminaryenquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_image', models.ImageField(upload_to='<function case_directory_path at 0x10b0e9170>/evidences/')),
                ('evidence_name', models.CharField(max_length=100)),
                ('evidence_desc', models.CharField(max_length=200)),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='DraftSheetAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=cases.models.draft_directory_path)),
                ('draft_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.draftchargesheetproposal')),
            ],
        ),
        migrations.CreateModel(
            name='DraftArticleAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=cases.models.draft_article_directory_path)),
                ('draft_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_attachments', to='cases.draftarticle')),
            ],
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='misconduct_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.natureofmisconduct'),
        ),
        migrations.CreateModel(
            name='ChargedOfficerAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=cases.models.charged_officer_directory_path)),
                ('charged_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.chargedofficer')),
            ],
        ),
        migrations.CreateModel(
            name='CaseIdentityAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=cases.models.case_identity_directory_path)),
                ('case_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.caseidentity')),
            ],
        ),
        migrations.AddField(
            model_name='caseidentity',
            name='nature_of_misconduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nature_of_misconduct_cases', to='cases.natureofmisconduct'),
        ),
        migrations.AddField(
            model_name='caseidentity',
            name='office',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='office_cases', to='accounts.office'),
        ),
        migrations.AddField(
            model_name='caseidentity',
            name='source_of_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_of_complaint_cases', to='cases.sourceofcomplaint'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_identity_case', to='cases.caseidentity'),
        ),
        migrations.AddField(
            model_name='case',
            name='charged_officer',
            field=models.ManyToManyField(related_name='charged_officer_cases', to='cases.ChargedOfficer'),
        ),
        migrations.AddField(
            model_name='case',
            name='draft_article',
            field=models.ManyToManyField(related_name='article_cases', to='cases.DraftArticle'),
        ),
    ]
