# Generated by Django 3.1.4 on 2021-02-11 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('ONGOING', 'Ongoing')], default='ONGOING', max_length=10),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_image', models.ImageField(upload_to='<function case_directory_path at 0x7f99f499aca0>/evidences/')),
                ('evidence_name', models.CharField(max_length=100)),
                ('evidence_desc', models.CharField(max_length=200)),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
