# Generated by Django 3.1.4 on 2021-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseidentity',
            name='case_identity_attachment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chargedofficer',
            name='charged_officer_attachment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='draftarticle',
            name='draft_article_attachment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='draftchargesheetproposal',
            name='draft_charge_sheet_proposal_attachments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryenquiry',
            name='preliminary_enquiry_attachment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
