# Generated by Django 3.1.4 on 2021-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliminaryenquiry',
            name='preliminary_enquiry_attachment_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
