# Generated by Django 3.1.4 on 2021-02-28 10:31

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_image',
            field=models.ImageField(upload_to=cases.models.case_directory_path),
        ),
    ]
