# Generated by Django 3.1.4 on 2021-02-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210211_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_image',
            field=models.ImageField(upload_to='<function case_directory_path at 0x7f5faf1cdca0>/evidences/'),
        ),
    ]
