# Generated by Django 3.1.4 on 2021-03-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210310_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftarticle',
            name='amount_involved_if_any',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
