# Generated by Django 3.1.4 on 2020-12-11 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201210_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='treasury_code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
